name: "✨ New epic"
description: Create a new ticket for a new epic.
title: "<title>"
labels: ["epic"]
projects: ["MartijnHagenaars/1"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Describe clearly what the epic should be about. 
    validations:
      required: true

  - type: textarea
    id: defofdone
    attributes:
      label: "Definition of done"
      description: Describe the definition of done. Write the acceptance criteria for when an epic can be considered done. 
      placeholder: |
        DoD: (example)
        1. The following features need to be researched: ...
        2. The following features need to be implemented: ...
        3. Documentation needs to be written about ...
        etc...
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: Take a look at the assignees, labels and milestones before submitting!
      
