name: "💭 Feature request"
description: Create a new ticket for discussing/requesting new features.
title: "<title>"
labels: [
  "feature request"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Provide a brief description of what you would like to see added to the project.
    validations:
      required: true

  - type: textarea
    id: defofdone
    attributes:
      label: "Why do we need this?"
      description: Describe why this feature is important for our project. Why should we implement it? How does it improve the project?
      placeholder: |
        We should implement this feature because...
        It will improve our project because...
        etc...
    validations:
      required: true
      
  - type: textarea
    id: additionalinfo
    attributes:
      label: "Additional info"
      description: Additional info.
      placeholder: Is there something else that needs to be mentioned? Write it here!
    validations:
      required: false
      
